#VARIABLE HOLD DATA
AGE = 15    # INT (INTEGER)
HEIGHT = 7.5  # FLOAT( DECIMAL)
NAME = "VICTOR"  #STR (STRING)
IS_STUDENT = TRUE #BOOL (BOOLEAN)

#PRINTING OUT VALUES
PRINT("NAME:",NAME)
PRINT("AGE:", AGE)
PRINT("HEIGHT:" ,HEIGHT)
PRINT("IS A STUDENT?" , IS_STUDENT)

